include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Good practices
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    annotate_overrides: true

analyzer:
  errors:
    # Treat these as warnings, not errors
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
