// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUY4r8AQmCw8_2quMqAwaLCAsYlD4k61c',
    appId: '1:669897121997:web:db21ff6ebe5c62fdeac984',
    messagingSenderId: '669897121997',
    projectId: 'daylight-wellbeing-app',
    authDomain: 'daylight-wellbeing-app.firebaseapp.com',
    storageBucket: 'daylight-wellbeing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLY71QwX4lRnKiYTEouyFIawd-SZtkp0',
    appId: '1:669897121997:android:4ad3fe93dc43eb24eac984',
    messagingSenderId: '669897121997',
    projectId: 'daylight-wellbeing-app',
    storageBucket: 'daylight-wellbeing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZz0NKxV8k3WSEGZl8osEvZv_eNhiScts',
    appId: '1:669897121997:ios:69dbad6ce3e19f42eac984',
    messagingSenderId: '669897121997',
    projectId: 'daylight-wellbeing-app',
    storageBucket: 'daylight-wellbeing-app.firebasestorage.app',
    androidClientId: '669897121997-8qg5d59iemktar64fj1fj02linlla9of.apps.googleusercontent.com',
    iosClientId: '669897121997-krmp6nsndhi1lmitevhmodhte0jf3a7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.daylightWellbeingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZz0NKxV8k3WSEGZl8osEvZv_eNhiScts',
    appId: '1:669897121997:ios:69dbad6ce3e19f42eac984',
    messagingSenderId: '669897121997',
    projectId: 'daylight-wellbeing-app',
    storageBucket: 'daylight-wellbeing-app.firebasestorage.app',
    androidClientId: '669897121997-8qg5d59iemktar64fj1fj02linlla9of.apps.googleusercontent.com',
    iosClientId: '669897121997-krmp6nsndhi1lmitevhmodhte0jf3a7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.daylightWellbeingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUY4r8AQmCw8_2quMqAwaLCAsYlD4k61c',
    appId: '1:669897121997:web:f3632cce851eb15deac984',
    messagingSenderId: '669897121997',
    projectId: 'daylight-wellbeing-app',
    authDomain: 'daylight-wellbeing-app.firebaseapp.com',
    storageBucket: 'daylight-wellbeing-app.firebasestorage.app',
  );

}